version: "3.3"

services:

  kodi:
    container_name: kodi
    image: linuxserver/kodi-headless
    restart: unless-stopped
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./kodi_data:/config/.kodi
    ports:
      - "8280:8080"
      - "9090:9090"
      - "9777:9777/udp"



