version: '3.3'
services:
  traefik:
    image: 'traefik:1.7.2-alpine'
    container_name: traefik   
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik.toml:/traefik.toml
        - ./acme.json:/acme.json
    ports:
        - '80:80'
        - '443:443'
    network_mode: web

