version: '3'
services:

*************************************** ADMINER *******************************************     
  adminer:
      image: adminer:$ADMINER_TAG
      container_name: "${PROJECT_NAME}_adminer"
      environment:
          # For PostgreSQL:
          #      ADMINER_DEFAULT_DB_DRIVER: pgsql
    #            some_database: mariadb
          ADMINER_DEFAULT_SERVER: mariadb                                #* puede que no valga
    #            ADMINER_DEFAULT_DB_HOST: $MOODLE_DOCKER_DBHOST            #* puede que no valga
    #            ADMINER_DEFAULT_DB_NAME: $DB_NAME                         #* puede que no valga
    #            ADMINER_PLUGINS0: 'tables-filter tinymce'
    #            ADMINER_PLUGINS: 'login-servers'
    #Create a file "/var/www/html/plugins-enabled/login-servers.php"
      ports:
          - 8100:8080
#      networks:
#          - Net_HL
      labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
#         - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"

