[http.middlewares.simpleAuth.basicAuth]
    users = [
    "roke:$apr1$FEeBnCCU$t2OEOggeDPgFQQk2bnK9H."
    ]
    
[http.routers.api]
    rule = "Host(`rokedegea.eu`)"
    entrypoints = ["websecure"]
    middlewares = ["simpleAuth"]
    service = "api@internal"
[http.routers.api.tls]
    certResolver = "lets-encrypt" 